version: '3.2'
services:
  kibana:
    image: kibana:7.6.1
    environment:
      SERVER_NAME: kibana
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.6.1
    environment:
      - cluster.name=pdk
      - node.name=es
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - discovery.type=single-node
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  esdata:
