version: '3'
services:
  kibana:
    image: kibana:7.6.1
    environment:
      SERVER_NAME: kibana
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.6.1
    environment:
      - cluster.name=pdk
      - node.name=pdk-es
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - discovery.type=single-node
    ports:
      - 9200:9200
